"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const FirstFunctionContainer_1 = require("./core/functions/FirstFunctionContainer");
const MethodInput_1 = require("./core/inputs/MethodInput");
const ChordsMethod_1 = require("./core/methods/ChordsMethod");
const SecondFunctionContainer_1 = require("./core/functions/SecondFunctionContainer");
const NewtonMethod_1 = require("./core/methods/NewtonMethod");
const MethodInputWithInitApprox_1 = require("./core/inputs/MethodInputWithInitApprox");
const SimpleIterationsMethod_1 = require("./core/methods/SimpleIterationsMethod");
const ThirdFunctionContainer_1 = require("./core/functions/ThirdFunctionContainer");
console.log("kek");
// let p: P = new P(null);
let firstFuncCont = new FirstFunctionContainer_1.FirstFunctionContainer();
let secondFuncCont = new SecondFunctionContainer_1.SecondFunctionContainer();
let thirdFuncCont = new ThirdFunctionContainer_1.ThirdFunctionContainer();
let input = new MethodInput_1.MethodInput(-3, -1, 0.001);
let inputWithInitApprox = new MethodInputWithInitApprox_1.MethodInputWithInitApprox(-30, 200, -2, 0.001);
// let validationResult: ValidationResult = FunctionInputValidator.validate(input,  firstFuncCont);
// console.log(validationResult);
let chordsMeth = new ChordsMethod_1.ChordsMethod();
let newtonMeth = new NewtonMethod_1.NewtonMethod();
let simpleIterationsMeth = new SimpleIterationsMethod_1.SimpleIterationsMethod();
let chordsMethResultTab = chordsMeth.calculate(input, thirdFuncCont);
let newtonMethResultTab = newtonMeth.calculate(inputWithInitApprox, thirdFuncCont);
let simpleIterationsMethResultTab = simpleIterationsMeth.calculate(inputWithInitApprox, thirdFuncCont);
console.log("Simple iterations methods res table : ", simpleIterationsMethResultTab);
console.log(" x = ", simpleIterationsMethResultTab.getFinalX());
console.log(" x = ", chordsMethResultTab.getFinalX());
console.log(" x = ", newtonMethResultTab.getFinalX());
console.log("*********************");
// console.log(MethodResultTableRenderer.render(chordsMethResultTab, 3, headings.chordsMethodResultTableHeadings))
console.log("Finished");
//# sourceMappingURL=main.js.map